### ISSUE TITLE
Thank you and a question

### ISSUE THREAD

**Issue by yns01** [brandur/rocket-rides-atomic#1]
Hello @brandur,

First of all, thank you for this article it's really great!

I do have one question; can somehow the call to Stripe end with a 409? 

Thanks

**Comment by brandur** [comment]
Hi @yns01,

I haven't thought about it in a while, but while it's possible, I don't think it's likely.

Stripe responds with a 409 if it thinks that a call is in-progress already for an idempotency key that you gave it. This is something that implementations run into often, but in the case of rocket-rides-atomic, it's implementing its own idempotency system that will make a 409 far less likely.

When a request comes in, rocket-rides-atomic locks an open idempotency key:

``` ruby
        # Lock the key and update latest run unless the request is already
        # finished.
        if key.recovery_point != RECOVERY_POINT_FINISHED
          key.update(last_run_at: Time.now, locked_at: Time.now)
        end
```

If a concurrent request tries to use the same key, it's denied:

``` ruby
        if key.locked_at && key.locked_at > Time.now - IDEMPOTENCY_KEY_LOCK_TIMEOUT
          halt 409, JSON.generate(wrap_error(Messages.error_request_in_progress))
        end
```

So only one key at a time is allowed into the critical section where the call to Stripe is being made, which by extension means that executing two calls out to Stripe for the same key (which would cause a 409) should be impossible.

Hope that helps!

**Comment by yns01** [comment]
Thanks @brandur, it does help :)

One more question, in your `atomic_phase` implementation you handle the `Sequel::SerializationFailure` by replying to the client with a 409 and you commented with `you could possibly retry this error instead`

I suppose that you meant to retry the block (i.e transaction), right? Also, I see how for the first atomic you could run into the `SerializationFailure`, but for the others, how would it be possible as only one request is allowed to lock the idempotency key at the beginning of the request (as you mentionned above)?

**Comment by brandur** [comment]
> I suppose that you meant to retry the block (i.e transaction), right?

Yep, exactly. You can even use the `retry` keyword in Ruby if you write this right.

> Also, I see how for the first atomic you could run into the SerializationFailure, but for the others, how would it be possible as only one request is allowed to lock the idempotency key at the beginning of the request (as you mentionned above)?

Ah, yeah. Because of the locking on idempotency key, it's probably not likely that the same key causes a failure of this sort given that only one request can be running at a time.

However, other things in the database could also cause a serialization failure. When you ask for a `SERIALIZABLE` transaction, Postgres starts to guarantee that any concurrent transactions could have been run repeatably. If not, one of them gets aborted.

As an example, imagine if you wanted to implement a Rocket Rides feature like Uber Pool and/or Lyft Line so that two riders could share a ride. You'd do this presumably by first scanning a set of active rides to find one with a location that's near where the current user is, and to add the user to a ride when one is found. Stay the sam looks like `SELECT * FROM rides WHERE active = true AND location =~ mine AND already_shared = false`.

Now imagine that two different potential riders were both close to a single active ride and in both cases Rocket Rides tried to add them to it. If you were on something like MongoDB, both operations would work because everything is inherently racy. But with Postgres and with `SERIALIZABLE` especially, one of those two operations fails: because our `SELECT * FROM rides ...` would have returned different results after one of the potential riders has claimed it (`already_shared` now equals `true`), Postgres knows to abort other operations that would have tainted the results. The unsuccessful rider will have to retry and look for a different match.

**Comment by yns01** [comment]
A bit late, but thanks for your explanations @brandur !

Btw, I also wanted to let you know that your blog articles are excellent reads! Hope to read more 😄

**Comment by brandur** [comment]
Thank you Yanis!
