### ISSUE TITLE
Serializable Isolation Level

### ISSUE THREAD

**Issue by sjmtan** [brandur/rocket-rides-atomic#12]
Brandur,

Thanks for this! I've been leveraging your content to understand what such a "generalized" framework would look like for our Postgres DB. 

One note though: is it required that the block executes with the serializable isolation level? Or just that the key update for lease/creation operates with serializable isolation level? I see this as causing performance issues if the underlying block was sufficiently complex.

You alluded to this I think here: https://news.ycombinator.com/item?id=15570016, and here:  https://github.com/brandur/rocket-rides-atomic/issues/1#issuecomment-352325233

> "I think alternatively using a `FOR UPDATE` is totally plausible and likely even to be more performant than what I've written here."

What are your thoughts on something like:

```
in a serializable transaction,
	find key
	if not present,
		create and "lock" using locked_at time
	else
		if key has result
			return result
		if locked_at time > now()
			return, can't run yet
		else
			update locked_at and continue

start another transaction (read committed):
	result = someFunc()
	update key with result
```

Because the first block ensures that this process is either allowed to run or not, we don't need a subsequent lock on the read committed transaction. This also avoids any lock contention (or growing lock queues) on the key.

**Comment by sjmtan** [comment]
@brandur - Apologies for tagging you, but would just really appreciate getting your input. Thanks!

**Comment by brandur** [comment]
Hi Shannon,

I should update this article to say something to this effect, but generally: I've amended my opinion since writing that, and would now say that you should step up to `SERIALIZABLE` with some care — i.e. for critical operations where you need to be especially careful, or in places that you know you're likely to need it.

I don't have too many real world data points to demonstrate problems with `SERIALIZABLE`, but I do have one. A fellow emailed me a while back saying that on a relatively hot path, he was seeing enough contention with `SERIALIZABLE` for it to be a problem (transactions would roll back and need to be retried with enough frequency that it was causing trouble).

Postgres' `SERIALIZABLE` is about as efficient of an implementation as you could possibly hope for it, but it's such a strong isolation level that just being very efficient might not be enough in a high-throughput OLTP system.

Your approach of a more precise use of `SERIALIZABLE` while dropping down to `READ COMMITTED` (or `REPEATED READ`) sounds plausible to me, and is probably closer to a better general purpose approach. If you end up implementing this, let me know how it works out.

**Comment by sjmtan** [comment]
Thanks @brandur.

I must say that a lot of my tech specs have a link to your posts. And so I'm smiling just from getting a response from you!

For context on content I've used from you:
- Idempotency
- Postgres connection pooling
- Rate limiting
- Transactionally staged job queues

Thanks again for all of the awesome content.

**Comment by brandur** [comment]
No worries at all Shannon!!

> For context on content I've used from you:
> - Idempotency
> - Postgres connection pooling
> - Rate limiting
> - Transactionally staged job queues

Holy :) That's incredible. Well, thanks for stopping by to say so — I can look at readership stats, but it's not all that often that people take the time to write back.
